package com.example.demo.Domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

// entity는 mysql의 테이블 및 컬럼을 자동생성 해주는 역할
@Entity
public class Member {

//    // pk + autogenerated 설정, Long은 bigint로 변환되어 생성된다
//    @Id
//    @GeneratedValue(strategy =  GenerationType.IDENTITY)
//    private Long id;
//
//    // String은 varchar로 변환되어 생성된다
//    private String name;
}
