# .properties ??? ???? ?? yml(??) ??? ???? ????.
# yml ??? ????? ???? ????? ????,

spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
  jpa:
    database: mysql
    # ?? mysql??? ????? InnoDB(??? ??)? ?? ?? ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # jpa ??? ?? ??, ???, ?? ? ????? ???? ??
    # ??? ddl ??? ???, ??? ????? ?? ??
    generate-ddl: true
    hibernate:
      ddl-auto: create
    # ? ?? show_sql: true ??? ????? ? ????? query? console? ???? ?
    show_sql: true