# .properties를 가독성이 좋은 yml로 변경

spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3300/board
    username: root
    password: 1234
  jpa:
    database: mysql
    # mysql 엔진 중에 일반적으로 많이 사용되는 InooDB를 사용하겠다는 설정
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # jpa 설정. ddl을 자동으로 적용하겠다는 설정
    generate-ddl: true
    hibernate:
    # create 옵션은 매번 table을 drop후 create
    # update 옵션은 변경사항만 alter를 적용
    # 현업에서는 validate 옵션으로 검증만 하는 경우가 대다수
      ddl-auto: update
    # jpa가 자동으로 쿼리를 생성할 때, 쿼리가 console창에 보여지도록 하는 설정
    show_sql: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml